version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mini_aspire_dev
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "14060:14060"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/mini_aspire_dev?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
