// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateBorrower(ctx context.Context, arg CreateBorrowerParams) (Borrower, error)
	CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBorrower(ctx context.Context, id int64) error
	DeleteLoan(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetBorrower(ctx context.Context, id int64) (Borrower, error)
	GetBorrowerByUserIdAndLoanId(ctx context.Context, arg GetBorrowerByUserIdAndLoanIdParams) (Borrower, error)
	GetLoan(ctx context.Context, id int64) (Loan, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListBorrower(ctx context.Context, arg ListBorrowerParams) ([]Borrower, error)
	ListDescBorrower(ctx context.Context, arg ListDescBorrowerParams) ([]Borrower, error)
	ListDescLoan(ctx context.Context, arg ListDescLoanParams) ([]Loan, error)
	ListDescPayment(ctx context.Context, arg ListDescPaymentParams) ([]Payment, error)
	ListDescUser(ctx context.Context, arg ListDescUserParams) ([]User, error)
	ListLoan(ctx context.Context, arg ListLoanParams) ([]Loan, error)
	ListPayment(ctx context.Context, arg ListPaymentParams) ([]Payment, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]User, error)
	UpdateBorrower(ctx context.Context, arg UpdateBorrowerParams) (Borrower, error)
	UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error)
	UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) (Loan, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
